---
- name: Install Package
  hosts: all
  vars:
  - package_name: httpd

  tasks:
  - name: install package {{ package_name }} for {{hostvars[inventory_hostname].ansible_ssh_host}} 
    yum: name={{ package_name }} state=present
