---
- name: Tag VM
  hosts: "{{ vm_target_name }}"
  vars: 
    user: admin
    password: smartvm
    vm_target_name:

  tasks:
  - debug: var=hostvars[inventory_hostname].cloudforms.href
  - debug: var=user
  - debug: var=password
  - debug: var=manageiq.api_url
  - debug: var=manageiq.api_token
  - debug: var=manageiq.service
  - debug: var=manageiq.event_target
  
  - name: Tag the VM
    uri:
      url: "{{ hostvars[inventory_hostname].cloudforms.href }}/tags"
      method: POST
      validate_certs: no
      force_basic_auth: yes
      user: "{{ user }}"
      password: "{{ password }}"
      body_format: json
      body:
        action: assign
        resources:
        - name: "/function/database"
    register: output
    
  - debug: var=output
